[package]
name = "ricochet-robots-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.214", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.93"
wasm-bindgen-test = "0.3.45"

[lib]
crate-type = ["cdylib", "rlib"]
